// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BibliotecaMVCEF.Models
{
    public partial class Obras
    {
        public Obras()
        {
            Requisicoes = new HashSet<Requisicoes>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("titulo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Titulo { get; set; }
        [Column("autor")]
        [StringLength(50)]
        [Unicode(false)]
        public string Autor { get; set; }
        [Column("genero")]
        [StringLength(50)]
        [Unicode(false)]
        public string Genero { get; set; }

        [InverseProperty("IdObraNavigation")]
        public virtual ICollection<Requisicoes> Requisicoes { get; set; }
    }
}